= Lecture Notes 22-23 / 1ahitm / SEW
Thomas W. Stütz
1.0.0, {docdate}: Softwareentwicklung
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left


//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Lehrplan

* https://www.ris.bka.gv.at/Dokumente/BgblAuth/BGBLA_2011_II_300/COO_2026_100_2_701387.pdfsig[Lehrplan 2011]


== 2022-09-22

.Java Quellcode
[source,java]
----
public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello World, 1ahitm!");
  }
}
----


.Zunächst wird der Quellcode compiliert
----
javac HelloWorld.java
----

.Man erhält ein class-File
----
ls -lh
----

.Ausgabe am Bildschirm
----
drwxr-xr-x   4 stuetz  staff   128B Sep 28 10:01 .
drwxrwxrwx@ 25 stuetz  staff   800B Sep 26 09:45 ..
-rw-r--r--   1 stuetz  staff   432B Sep 28 10:01 HelloWorld.class
-rw-r--r--   1 stuetz  staff   121B Sep 15 09:44 HelloWorld.java
----

----
java HelloWorld
----

.Ausgabe am Bildschirm
----
Hello World, 1ahitm!
----


== 2022-09-28 (Mi.)

* Supplierung Prof. Köck

[source,java]
----
import java.util.Scanner;

public class Ue01_HelloWorld {
    public static void main(String[] args) {
        // Delaration einer Variable:
        //    Anlegen einer neuen Variable
        //    mit dem Namen 'name'
        //    vom Typ 'String'
        String name;
        // Zuweisung eines Werts zu einer Variable
        name = "Johann";

        // Alternative: Deklaration und Erstzuweisung in einer Anweisung
        // String name = "Johann";

        // Ask user for his/her name
        System.out.print("What's your name? ");
        Scanner sc = new Scanner(System.in);
        name = sc.nextLine();



        // + ist ein Textverknüpfungs-Operator
        System.out.println("Hello, " + name + "!");
    }
}
----

[source,java]
----
import java.util.Scanner;

public class Ue02_AddNumbers {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        //Zahlen-Datentyp
        //int number1;
        //sc.nextInt();

        // Gib die 1. Zahl ein: 13
        // Gib die 2. Zahl ein: 17
        // 13 + 17 = 30

        // Declare variables
        int number1;
        int number2;
        int sum;

        // Get numbers from user
        System.out.print("Gib die 1. Zahl ein: ");
        number1 = sc.nextInt();
        System.out.print("Gib die 2. Zahl ein: ");
        number2 = sc.nextInt();

        // Calculate sum
        sum = number1 + number2;

        // Print calculation and result
        System.out.println(number1 + number2 + " = " + sum);

        // Wenn fertig:
        // Neues Projekt: Ue03_Waehrungsumrechnung
        // EURO-Betrag wird eingelesen und in GBP und USD umgewandelt
        // Aktuelle Wechselkurs im Internet recherchieren
    }
}
----


== 2022-09-29 (Do.)

* Praktischer Unterricht mit Aistleitner, Köck, Stütz

<<uebung04.adoc#,Übung 04 - Vorbereiten des Toolings>>

* Anmelden bei github


== 2022-10-04 (Di.)

* Was ist ein Variable: 02 Grundlagen.pdf

////
<<visitenkarte.adoc#,Übung 05 - Visitenkarte>>

<<taschenrechner.adoc#,Übung 06 - Taschenrechner>>
////

== 2022-10-04

* Grundlagen der Formatierung (System.out.printf(...))
* Aus**checken** der Übung
* Öffnen in der IDE


== 2022-10-05 (Supplierung Prof. Köck)

.Angabe Turmrechnen
[%collapsible]
====
Schreiben Sie ein Programm, das eine ganze Zahl einliest und für diese Zahl eine Turmrechnung durchführt und alle Zwischenergebnisse ausgibt.

Bei der Turmrechnung wird die eingegebene Basiszahl mit 2, 3, … 9 der Reihe nach multipliziert, anschließend durch 2, 3, … 9 dividiert, sodass am Ende wieder die Basiszahl entsteht.

Hinweise:

* Nutzen Sie nur die im Unterricht verwendeten Programmkonzepte!
* Verwenden Sie einen möglichst großen, ganzzahligen Datentyp!
* Fehler, welche durch eine zu große Basiszahl verursacht werden, können ignoriert werden!
* Beachten Sie die Abgaberichtlinien!

----
Beispielausgabe:
Bitte Zahl eingeben: 1234

Turmrechnung
============
1234 | *2
2468 | *3
7404 | *4
29616 | *5
148080 | *6
888480 | *7
6219360 | *8
49754880 | *9
447793920 | /2
223896960 | /3
74632320 | /4
18658080 | /5
3731616 | /6
621936 | /7
88848 | /8
11106 | /9
1234

Turmrechnung formatiert
=======================
            1234  | * 2
            2468  | * 3
            7404  | * 4
           29616  | * 5
          148080  | * 6
          888480  | * 7
         6219360  | * 8
        49754880  | * 9
       447793920  | / 2
       223896960  | / 3
        74632320  | / 4
        18658080  | / 5
         3731616  | / 6
          621936  | / 7
           88848  | / 8
           11106  | / 9
            1234  |
----
====


.Source Code Turmrechnen
[%collapsible]
====
[source,java]
----
import java.util.Scanner;

public class Ue04_Turmrechnen {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        // get base-number from user
        System.out.print("Bitte Zahl eingeben: ");
        long number = sc.nextLong();

        // calculation
        System.out.println("");
        System.out.println("Turmrechnung");
        System.out.println("============");
        System.out.println(number + " | *" + 2 );
        number = number * 2;
        System.out.println(number + " | *" + 3 );
        number = number * 3;
        System.out.println(number + " | *" + 4 );
        number = number * 4;
        System.out.println(number + " | *" + 5 );
        number = number * 5;
        System.out.println(number + " | *" + 6 );
        number = number * 6;
        System.out.println(number + " | *" + 7 );
        number = number * 7;
        System.out.println(number + " | *" + 8 );
        number = number * 8;
        System.out.println(number + " | *" + 9 );
        number = number * 9;
        System.out.println(number + " | /" + 2 );
        number = number / 2;
        System.out.println(number + " | /" + 3 );
        number = number / 3;
        System.out.println(number + " | /" + 4 );
        number = number / 4;
        System.out.println(number + " | /" + 5 );
        number = number / 5;
        System.out.println(number + " | /" + 6 );
        number = number / 6;
        System.out.println(number + " | /" + 7 );
        number = number / 7;
        System.out.println(number + " | /" + 8 );
        number = number / 8;
        System.out.println(number + " | /" + 9 );
        number = number / 9;
        System.out.println(number);

        // calculation with format
        System.out.println("");
        System.out.println("Turmrechnung formatiert");
        System.out.println("=======================");
        System.out.printf("%16d  | * %d%n" , number,  2 );
        number = number * 2;
        System.out.printf("%16d  | * %d%n" , number,  3 );
        number = number * 3;
        System.out.printf("%16d  | * %d%n" , number,  4 );
        number = number * 4;
        System.out.printf("%16d  | * %d%n" , number,  5 );
        number = number * 5;
        System.out.printf("%16d  | * %d%n" , number,  6 );
        number = number * 6;
        System.out.printf("%16d  | * %d%n" , number,  7 );
        number = number * 7;
        System.out.printf("%16d  | * %d%n" , number,  8 );
        number = number * 8;
        System.out.printf("%16d  | * %d%n" , number,  9 );
        number = number * 9;
        System.out.printf("%16d  | / %d%n" , number,  2 );
        number = number / 2;
        System.out.printf("%16d  | / %d%n" , number,  3 );
        number = number / 3;
        System.out.printf("%16d  | / %d%n" , number,  4 );
        number = number / 4;
        System.out.printf("%16d  | / %d%n" , number,  5 );
        number = number / 5;
        System.out.printf("%16d  | / %d%n" , number,  6 );
        number = number / 6;
        System.out.printf("%16d  | / %d%n" , number,  7 );
        number = number / 7;
        System.out.printf("%16d  | / %d%n" , number,  8 );
        number = number / 8;
        System.out.printf("%16d  | / %d%n" , number,  9 );
        number = number / 9;
        System.out.printf("%16d  |%n" , number );
    }
}
----
====


== 2022-10-13 (Do.)

=== Verzweigungen

* = -> Zuweisung, zB `age = 18;`
* == -> Vergleich zB `if (a == b) { ... }`
** bei Zeichenketten `equals` verwenden!!!


* IDE
** Integrierte Entwicklungsumgebung
** Integrated Development Environment



=== Modulo - Operator

* Der Operator für eine Division ist ein `/`

** zB `int teiler = 10 % 2;`

* Es gibt auch einen Operator, um den Rest einer Division zu erhalten:

** Modulo-Operator -> `%`
** int divisionsrest = 10 / 3;














////
[plantuml,cld,png]
----
include::plantuml/cld.puml[]
----
////