= Taschenrechner

== Lehrziele

- Die Verwendung der Datentypen int und double und eines einfachen Rechenoperators (+).
- Die Ausgabe von Texten und formatierten Zahlen auf die Konsole.

== Aufgabenstellung

=== 1. Addition ganzer Zahlen

Schreiben Sie ein Programm in der Quellcode-Datei ```Calculator.java```, welches zwei ganze Zahlen von der Konsole einliest,  diese beiden Zahlen addiert, und die gesamte Rechnung rechtsbündig formatiert auf die Konsole ausgibt.

==== Beispiel:

[source]
---------------------
************************************
* Calculator - Ihr Zahlenbegleiter *
************************************

Erste Ganzzahl  : -565433
Zweite Ganzzahl : 89826

Ergebnis:
=========
             -565433
+              89826
--------------------
             -475607
====================
---------------------

==== Hinweise

- Testen Sie das Programm ausführlich mit sehr großen und sehr kleinen, also positiven und negativen ganzen Zahlen.
- Finden Sie heraus, wieviel Platz Sie für die größte und die kleinste Zahl benötigen! Nach dem Rechenoperator „+“ sollte noch ein Leerzeichen Platz finden, bevor die Zahl beginnt.


=== 2. Addition von Gleitkommazahlen

Erstellen Sie ein neues Programm in der Datei ```FloatingPointCalculator.java```, welches denselben Ablauf vorsieht wie in Aufgabe 1, allerdings werden diesmal Gleitkommazahlen anstelle von ganzen Zahlen addiert. Bei der Ausgabe der Rechnung auf die Konsole sollen dabei fix 4 Nachkommastellen vorgesehen werden.

==== Beispiel:

[source]
---------------------
************************************
* Calculator - Ihr Zahlenbegleiter *
************************************

Erste Dezimalzahl  : 23612.34732
Zweite Dezimalzahl : 26213.34643

Ergebnis:
=========
          23612.3473
+         26213.3464
--------------------
          49825.6938
====================
---------------------

==== Hinweise:

- Testen Sie das Programm wieder ausführlich mit sehr großen und sehr kleinen, also positiven und negativen Gleitkommazahlen.
- Da dieser Datentyp wirklich sehr sehr große und kleine Zahlen darstellen kann, reicht es bei diesem Beispiel, ca. 20 Stellen vor dem Komma bei der Ausgabe vorzusehen. Nach dem Rechenoperator „+“ sollte noch ein Leerzeichen Platz finden, bevor die Zahl beginnt.
